<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Republish</name>
   <tag></tag>
   <elementGuidId>2b65fd4f-bb41-4811-bedb-a8660336ad0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ms-Button-flexContainer.flexContainer-138</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='spCommandBar']/div/div/div/div/div/div[2]/div[3]/div/div/button/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Republish' or . = 'Republish')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f3992a1c-6471-468b-8862-cc4b6b7b18c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Button-flexContainer flexContainer-138</value>
      <webElementGuid>64f99372-a181-4ec1-adfc-d97f0a35b092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automationid</name>
      <type>Main</type>
      <value>splitbuttonprimary</value>
      <webElementGuid>04c267f8-f360-46ae-b7ef-d49d7476848b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Republish</value>
      <webElementGuid>a07a2ce2-a34c-4729-832a-0a90ff5ab9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spCommandBar&quot;)/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;ms-FocusZone css-77 ms-CommandBar root-119&quot;]/div[@class=&quot;ms-OverflowSet ms-CommandBar-secondaryCommand secondarySet-135&quot;]/div[@class=&quot;ms-OverflowSet-item item-123&quot;]/div[@class=&quot;ms-TooltipHost PublishTooltipHost PublishTooltipHostColumn root-76&quot;]/div[@class=&quot;primaryCommandBarButtonWrapper&quot;]/button[@class=&quot;ms-Button ms-Button--primary primaryButton primaryCommandBarButtonSpacing root-137&quot;]/span[@class=&quot;ms-Button-flexContainer flexContainer-138&quot;]</value>
      <webElementGuid>82a45c85-f30f-4949-bc63-a4d9ae8e666c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='spCommandBar']/div/div/div/div/div/div[2]/div[3]/div/div/button/span</value>
      <webElementGuid>1bf0f6ae-8230-4908-a290-f870e6ad2c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button/span</value>
      <webElementGuid>a7bc6f47-b046-49ef-87a4-04775442c87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Republish' or . = 'Republish')]</value>
      <webElementGuid>6698a3d6-5447-4284-bcfb-2c0222d5b634</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
