<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_closeWelcomeScreen</name>
   <tag></tag>
   <elementGuidId>427f8ca1-f613-4424-850c-501d39bdfda6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ModalFocusTrapZone163']/div[2]/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ms-Button.ms-Button--icon.root-286 > span.ms-Button-flexContainer.flexContainer-138</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0af02ae2-b698-4746-bc91-967c73a9d909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Button-flexContainer flexContainer-138</value>
      <webElementGuid>79a65390-009b-4bc1-855c-ec12385091f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automationid</name>
      <type>Main</type>
      <value>splitbuttonprimary</value>
      <webElementGuid>3aba362b-5dc4-487b-ba41-21b291230f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>575cc1aa-8119-4b11-ae83-e78d067d664e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ModalFocusTrapZone163&quot;)/div[@class=&quot;ms-Modal-scrollableContent scrollableContent-279&quot;]/div[@class=&quot;header-183&quot;]/button[@class=&quot;ms-Button ms-Button--icon root-286&quot;]/span[@class=&quot;ms-Button-flexContainer flexContainer-138&quot;]</value>
      <webElementGuid>bedec7b9-3784-4a6b-932e-b7bb9e7c02ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ModalFocusTrapZone163']/div[2]/div/button/span</value>
      <webElementGuid>9b054b01-dc3c-4732-acb2-5183429f666b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/button/span</value>
      <webElementGuid>4d3eb27f-4e6b-44e9-9eb7-bc62c87ddd41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '' or . = '')]</value>
      <webElementGuid>ab1ed3fa-bad0-4a45-9eb3-9ec0731ae567</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
