<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_moreoptions</name>
   <tag></tag>
   <elementGuidId>e82f8da9-c744-435d-b21e-5c54197b29c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>dc905847-b0aa-495a-ac6a-c68fb331ccf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e5225ba2-a21a-4ca0-9a56-06f33166e22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>08ad6dca-a5e5-4e68-8272-95b02def2fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2</value>
      <webElementGuid>92e40a62-31d5-470c-a5e6-105d7d034fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>clipboard-read;clipboard-write;geolocation</value>
      <webElementGuid>7d4f599d-dfaa-4ed4-8377-dd35a46c45c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>c9878752-ee88-456c-83fb-5124ee809458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>66eb29a5-ee31-44ad-9d1b-cb6434b84cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(13).aspx?Mode=Edit&amp;isEditMode=1&amp;isInTeams=0&amp;isInBrowser=1</value>
      <webElementGuid>df3db092-85a2-45ab-8a39-7c3238a42192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&quot;)</value>
      <webElementGuid>ced6e2e7-8624-48ba-9834-21bc4474e13b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']</value>
      <webElementGuid>51164641-cddd-4b6d-aa74-c9353d5099ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']/div[3]/div/div/iframe</value>
      <webElementGuid>b88ef01b-a895-41e2-9e54-e1fffe7dfe15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cfe350d2-14e7-4da3-9d2b-9b814a9fcec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2' and @src = 'https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(13).aspx?Mode=Edit&amp;isEditMode=1&amp;isInTeams=0&amp;isInBrowser=1']</value>
      <webElementGuid>903a9643-4abb-4cd2-a0fc-716bca6d469a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
