<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_searchSP</name>
   <tag></tag>
   <elementGuidId>52f2b4f7-3971-4cb7-88da-318283567a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#field-r8__control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div/div[3]/div[3]/div/div/div/div/span/input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;field-r8__control&quot;)[count(. | //*[@placeholder = 'Search' and @id = 'field-r8__control' and @ref_element = 'Object Repository/searchSP/Page_Test/iframe__searchSP']) = count(//*[@placeholder = 'Search' and @id = 'field-r8__control' and @ref_element = 'Object Repository/searchSP/Page_Test/iframe__searchSP'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa646c0d-796a-4d44-95bf-f4ed6b8e9948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db8d1a0b-971f-4803-bdeb-1c078a40f3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>8fcff7b5-9a7a-4980-84fe-62f6f000bbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-r8__control</value>
      <webElementGuid>13be489c-31c3-40ff-91a3-7009e75f522a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fui-Input__input rvp2gzh</value>
      <webElementGuid>d530f8bd-0e4d-4f3a-8e33-9f8993f52b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-r8__control&quot;)</value>
      <webElementGuid>33181e3b-7457-41b4-b3e4-f040488664b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/searchSP/Page_Test/iframe__searchSP</value>
      <webElementGuid>3313d36e-60ec-4ff2-9173-898c67d593f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-r8__control']</value>
      <webElementGuid>c834bb79-5fb6-4ed3-881b-91b83fd1a7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div[3]/div[3]/div/div/div/div/span/input</value>
      <webElementGuid>30cc2bec-67e0-4375-b2d7-7fbbda3f19ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>30beaca6-4417-43ea-bc82-778ab2ef207a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search' and @id = 'field-r8__control']</value>
      <webElementGuid>7a7ad5d3-ac09-4e01-bba5-1ad1a992c2c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
