<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__addFromSP</name>
   <tag></tag>
   <elementGuidId>f4de9f3b-78a3-40f6-aa12-a3e2b7c84199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#esri-map-3e28d587-e38a-48df-847b-1596b430a52f</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//iframe)[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@src = 'https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=3e28d587-e38a-48df-847b-1596b430a52f&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(14).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>bc1543e7-7c69-4c10-83f4-b584edea9197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b486babd-0073-4600-9b60-2330ee3b930a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f1c7318e-afe1-4b9d-b6a3-697d14339f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>esri-map-3e28d587-e38a-48df-847b-1596b430a52f</value>
      <webElementGuid>d350b1ed-e305-48c7-b6eb-4bc602f19fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>clipboard-read;clipboard-write;geolocation</value>
      <webElementGuid>00d4f0d2-0f99-44d4-9fa8-42e4b636f64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>655d81c8-1cfc-427e-a219-faf27b7c0893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>9b4e35a9-79c9-4334-97d3-488391c6bb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=3e28d587-e38a-48df-847b-1596b430a52f&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(14).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1</value>
      <webElementGuid>a3f39080-cdff-46a2-9da9-d2650bfdfb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;esri-map-3e28d587-e38a-48df-847b-1596b430a52f&quot;)</value>
      <webElementGuid>db5dfea3-93bc-4bc8-ab13-bc5ae1ec4c69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='esri-map-3e28d587-e38a-48df-847b-1596b430a52f']</value>
      <webElementGuid>a4d7c5cd-f6ee-4bd0-b01c-a2888acd1ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vpc_WebPart.ArcGisMapsWebPart.external.3e28d587-e38a-48df-847b-1596b430a52f']/div/div/iframe</value>
      <webElementGuid>9840d034-d54e-40b0-9844-da3b99e43325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>77cb5d11-51ed-4bee-835d-45e62cbb9d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'esri-map-3e28d587-e38a-48df-847b-1596b430a52f' and @src = 'https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=3e28d587-e38a-48df-847b-1596b430a52f&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(14).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1']</value>
      <webElementGuid>43fa6498-a8ce-4a32-bc94-1fa6f627655c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
