<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Home</name>
   <tag></tag>
   <elementGuidId>2dc0d34b-cb7f-455d-870b-25576ade0cea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div[3]/div/div[4]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.esri-component.esri-home.esri-widget--button.esri-widget</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c12052b5-ce80-4a4a-a7b2-2d0125ea6c7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>esri-component esri-home esri-widget--button esri-widget</value>
      <webElementGuid>51f845f0-2879-4515-b4d4-5ef75a38ab33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f69c77dc-e05f-427f-8526-a8b36c6f5459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7189eb6b-3099-4449-8c20-6b4fc7dac179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>72e6f7fb-1312-4b4e-8238-f183dcb6a700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Default extent</value>
      <webElementGuid>20aa3533-acdd-42b9-81ef-3580fed1de59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;fui-FluentProvider fui-FluentProviderr0 ___95gtr90 f19n0e5 f1vbcewu f1o700av fk6fouc fkhj508 figsok6 f1i3iumi fly5x3f f1l02sjl&quot;]/div[@class=&quot;___100chc6 fly5x3f f1l02sjl&quot;]/div[@class=&quot;___100chc6 fly5x3f f1l02sjl esri-view esri-view-width-xlarge esri-view-width-greater-than-xsmall esri-view-width-greater-than-small esri-view-width-greater-than-medium esri-view-width-greater-than-large esri-view-height-small esri-view-height-greater-than-xsmall esri-view-height-less-than-medium esri-view-height-less-than-large esri-view-height-less-than-xlarge esri-view-orientation-landscape&quot;]/div[@class=&quot;esri-view-root&quot;]/div[@class=&quot;esri-ui calcite-mode-light&quot;]/div[@class=&quot;esri-ui-inner-container esri-ui-corner-container&quot;]/div[@class=&quot;esri-ui-bottom-right esri-ui-corner&quot;]/div[@class=&quot;esri-component esri-home esri-widget--button esri-widget&quot;]</value>
      <webElementGuid>05019650-d378-4b69-8a2c-a71a55d97e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/homeButton/Page_Test/iframe__HomeButton</value>
      <webElementGuid>1c6d91c8-9e51-4ad8-a854-86025abfd8a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div[3]/div/div[4]/div</value>
      <webElementGuid>7c8a5395-be18-45c7-8a6d-b0543d2d6242</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[4]/div</value>
      <webElementGuid>6ac5a9b4-609f-4c9f-89e2-ba45426bfaaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Default extent']</value>
      <webElementGuid>4ae86d48-6fa6-4b58-aba0-310a7ce4ac87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
