<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__HomeButton</name>
   <tag></tag>
   <elementGuidId>8a6d8bff-5cb8-4079-9ba8-6be5b5a97d54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>44582aab-c5a9-44d4-8b86-84ccf648b6b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c7bde4ab-dc42-490a-940d-0139ce554484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>678c06a0-0c74-4244-9a79-3e51d13c488e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2</value>
      <webElementGuid>7523f025-4a07-492b-99eb-11a8ae59cefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>clipboard-read;clipboard-write;geolocation</value>
      <webElementGuid>ab02b667-2b76-42d8-8548-804217473593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>76afd902-ec15-4f57-af73-2e014aab9c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>7f3c7bd2-e898-47e1-90ac-087e6e2f0952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(13).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1</value>
      <webElementGuid>a5052ba9-0b40-45a6-add5-dbc228fa5fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&quot;)</value>
      <webElementGuid>3c96acda-a5ff-4df2-97d1-4fb0801262fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']</value>
      <webElementGuid>144e9b60-2a23-4f39-ac13-58977fa1fb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vpc_WebPart.ArcGisMapsWebPart.external.8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']/div/div/iframe</value>
      <webElementGuid>f11cf51d-a3f9-4750-835b-2d78e85fc0b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4e404c6d-61f3-4dfe-bd48-840fc9f544fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2' and @src = 'https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(13).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1']</value>
      <webElementGuid>e06e2441-5390-4ffa-ae14-9c1bc2f1365e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
