<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Republish</name>
   <tag></tag>
   <elementGuidId>747a484b-0d85-4bb7-84f3-c56805ddaca0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='Republish']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;Republish&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8b6eb00a-0f7a-4734-a2db-bfd9912e9756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33868a69-269a-4279-b060-9eb15548cb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Republish</value>
      <webElementGuid>86c4c279-0838-4804-9dc3-37bc37ec45d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Button ms-Button--primary primaryButton primaryCommandBarButtonSpacing root-185</value>
      <webElementGuid>fbba308d-4112-4407-9c8e-6005d4594824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>074bada2-4eef-483b-9eb3-9be435b5e8da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>pageCommandBarPublishButton</value>
      <webElementGuid>51f2305d-a035-4002-b421-f62ad57228a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-republish</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5d6a109d-7af7-49e8-889e-c7c27a630f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Republish. This will check in your changes so that everyone who has access to your page will be able to see them.</value>
      <webElementGuid>f86313ba-4003-4101-98b4-3b26767b7586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-is-focusable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42af5263-f8dc-4cee-aa0e-c9c1e7dfa435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9f4fab53-12df-4292-9def-c4408beaec66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Republish</value>
      <webElementGuid>a6b3caeb-fd82-49d7-bb0a-a8605281cae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spCommandBar&quot;)/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;ms-FocusZone css-77 ms-CommandBar root-119&quot;]/div[@class=&quot;ms-OverflowSet ms-CommandBar-secondaryCommand secondarySet-135&quot;]/div[@class=&quot;ms-OverflowSet-item item-123&quot;]/div[@class=&quot;ms-TooltipHost PublishTooltipHost PublishTooltipHostColumn root-76&quot;]/div[@class=&quot;primaryCommandBarButtonWrapper&quot;]/button[@class=&quot;ms-Button ms-Button--primary primaryButton primaryCommandBarButtonSpacing root-185&quot;]</value>
      <webElementGuid>26aa4b96-9c7f-4439-8d7b-7ab6881a0ff5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='Republish']</value>
      <webElementGuid>b2067025-cfc0-4a48-bc20-fbe9e331f15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='spCommandBar']/div/div/div/div/div/div[2]/div[3]/div/div/button</value>
      <webElementGuid>dfa62b4e-9568-4c29-af9d-0dc4785a172d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/button</value>
      <webElementGuid>83257558-7c56-4b19-aa52-027c39f85031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'Republish' and (text() = 'Republish' or . = 'Republish')]</value>
      <webElementGuid>302995a6-2fe1-4c8b-a139-4320c2e7995e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
