<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__layer1MoreOptions</name>
   <tag></tag>
   <elementGuidId>ee5d56f0-6a42-4fb2-b8d3-d44586389779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fed0f2fa-cce5-4885-ab47-8dd6540e15c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e39ef978-7332-4de5-86fe-c3f1a0bf8740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5792a69d-61e3-498c-bda5-a2c7be091434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2</value>
      <webElementGuid>36cacc99-185f-477f-b601-6a957d4ecc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>clipboard-read;clipboard-write;geolocation</value>
      <webElementGuid>3e432645-8939-4f3d-be15-f5b4611fda16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>353db5af-abbc-48de-8346-0b4f0a05824e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>ca06151c-f0e0-4c56-bc98-1875d73434e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(13).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1</value>
      <webElementGuid>1b957d67-7e8b-47df-a54b-7c8b02c4365a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&quot;)</value>
      <webElementGuid>c9ac74ac-750d-4953-8f28-a8077fffaa3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']</value>
      <webElementGuid>b626509c-7836-44b4-8e22-41a047e72d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vpc_WebPart.ArcGisMapsWebPart.external.8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']/div/div/iframe</value>
      <webElementGuid>71308dca-5971-46d7-a003-6d6ff3c96ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ed09e3f3-0210-432a-aa2c-61deef2dfd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2' and @src = 'https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(13).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1']</value>
      <webElementGuid>33140853-e57b-4a52-8c05-0522a7de6fc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
