<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__layer2_zoom</name>
   <tag></tag>
   <elementGuidId>feac94a4-ac86-4bdc-a314-efcc9dcd5008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>826a8f7c-526e-4c55-b839-cca593f57249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>27047a3b-3d6e-4c9b-ada5-4c55806a5722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>d2438d2e-3f6a-4dcb-9350-e6ed28ff3cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2</value>
      <webElementGuid>f611bdf2-e0d9-41f2-8d5d-c35031a2aa01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>clipboard-read;clipboard-write;geolocation</value>
      <webElementGuid>d682d114-2ea6-4f25-8f02-ac8d20d53e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>3d61141a-0494-4d49-b055-9f693a8b7344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>2d29c6d6-88a2-498b-a742-acd6c95598f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(13).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1</value>
      <webElementGuid>8169b66f-fa57-4081-8fe2-82e0d24a086c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&quot;)</value>
      <webElementGuid>df69da52-b0aa-4336-8e5a-3e037955c4c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']</value>
      <webElementGuid>2d68ba3f-b69f-4648-bd6b-33b153283db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vpc_WebPart.ArcGisMapsWebPart.external.8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']/div/div/iframe</value>
      <webElementGuid>3a061817-9e26-4f26-8ade-456f1d1ed108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>48891f90-8e86-4e85-b929-60a158bf53b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2' and @src = 'https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(13).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1']</value>
      <webElementGuid>4ec632ae-2859-43ea-ac82-3171298d4025</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
