<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__layer2_moreoptions</name>
   <tag></tag>
   <elementGuidId>8ba4a06f-5b45-4ebb-8a8d-2a9eac8bb897</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>2b8786b1-08a3-4727-9e5e-b73213a37067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6a8b033c-1628-499d-9e04-197b89716cf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5666a274-aaa4-4b08-b088-89a86b505cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2</value>
      <webElementGuid>648abcfd-cc62-4277-bd85-74df00212b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>clipboard-read;clipboard-write;geolocation</value>
      <webElementGuid>ba4dd627-0cf4-4d9d-84db-0b17780a2d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>a87586bf-ab23-4eb5-a5f7-99ef6a9e9d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>ab302b98-42db-49a1-be40-1e4bee1e1929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(13).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1</value>
      <webElementGuid>cfa7f341-21d7-4183-97ba-53d45d841934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&quot;)</value>
      <webElementGuid>99ee52ef-eef6-49e2-aa55-29a9cdd927b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']</value>
      <webElementGuid>6ecf24cc-7cf7-431e-a174-8c9bcd36977d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vpc_WebPart.ArcGisMapsWebPart.external.8f1a332b-4c8f-42c8-a801-bf2df2a43ee2']/div/div/iframe</value>
      <webElementGuid>a3c4e4f9-f1fb-406d-a99b-d50fab7973df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>6043751e-e2ae-4c2a-b3c3-cc2ff5d2c967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'esri-map-8f1a332b-4c8f-42c8-a801-bf2df2a43ee2' and @src = 'https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=8f1a332b-4c8f-42c8-a801-bf2df2a43ee2&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(13).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1']</value>
      <webElementGuid>8c7450ee-498f-441f-81f7-6759e06087e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
