<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_searchArcGIS</name>
   <tag></tag>
   <elementGuidId>03655991-1e80-4355-b1b6-799f364353c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='field-rn__control']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#field-rn__control</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>696c727b-8bc4-4b63-9cd2-56adbc7dadc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b3f150d-90f5-40f3-935c-8a3b06e04c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search ArcGIS Online</value>
      <webElementGuid>952abf72-4810-4ccd-8f53-091f835553c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>field-rn__control</value>
      <webElementGuid>b05c8130-4f79-41fc-9814-dd594fc9e846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fui-Input__input rvp2gzh</value>
      <webElementGuid>45d7323f-f7c8-4829-85fe-fdf470133b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;field-rn__control&quot;)</value>
      <webElementGuid>0f9786d5-7487-46de-b9e8-6248462be055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/searchArcGIS/Page_Test/iframe__searchArcGIS</value>
      <webElementGuid>20705a75-aa6c-4dbf-badb-8ad3abe839f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='field-rn__control']</value>
      <webElementGuid>72716e38-7ceb-4a6e-9f42-180089f5f063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div[3]/div[3]/div/div/div/div/div/span/input</value>
      <webElementGuid>fb3f88f2-574e-4b3c-b5f7-d23f425bdd84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>aaba1864-d03c-4c66-8c62-6eaa4c15a749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search ArcGIS Online' and @id = 'field-rn__control']</value>
      <webElementGuid>1b82443f-058d-43d1-a9c5-2b328f755fea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
