<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__expandLayer</name>
   <tag></tag>
   <elementGuidId>82895dd9-9736-4d64-9961-75baebd5b57f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//iframe)[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#esri-map-3e28d587-e38a-48df-847b-1596b430a52f</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>60907244-0945-4166-bf89-7f8bcb07ced3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5934dafb-ea17-4416-8897-cd1d21dba639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c9ae096c-d507-450e-80c2-c50cd7045e91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>esri-map-3e28d587-e38a-48df-847b-1596b430a52f</value>
      <webElementGuid>c3f3337f-1bfa-43c0-b454-b14328d8de04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>clipboard-read;clipboard-write;geolocation</value>
      <webElementGuid>149f078c-2265-4481-94a5-11751e217432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>564d1fec-3c30-4312-8ee4-e154560b3d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>84f6f5ce-5285-4c9d-82de-a6187cea2314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=3e28d587-e38a-48df-847b-1596b430a52f&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(14).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1</value>
      <webElementGuid>7c0dc9cc-9cfa-490f-86fd-000bb0b67884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;esri-map-3e28d587-e38a-48df-847b-1596b430a52f&quot;)</value>
      <webElementGuid>3a06014f-e143-441c-a55d-34d6560fa289</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='esri-map-3e28d587-e38a-48df-847b-1596b430a52f']</value>
      <webElementGuid>c7dd642e-9466-4905-9143-1ce73d1b5ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vpc_WebPart.ArcGisMapsWebPart.external.3e28d587-e38a-48df-847b-1596b430a52f']/div/div/iframe</value>
      <webElementGuid>eb8ce24f-8585-485b-9f36-90e9a5e17d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0c402f1d-807e-4fcc-8e71-2ad81dc2bc1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'esri-map-3e28d587-e38a-48df-847b-1596b430a52f' and @src = 'https://skywalker.esri.com/emaf/SP3097/reactapp/?webpartInstanceId=3e28d587-e38a-48df-847b-1596b430a52f&amp;isVisitor=0&amp;3d=0&amp;locale=en-us&amp;parentOrigin=https://m4o365.sharepoint.com/sites/raaj2/SitePages/Test(14).aspx&amp;isEditMode=0&amp;isInTeams=0&amp;isInBrowser=1']</value>
      <webElementGuid>a00dfdfb-98f5-4d0c-9f61-8c533cbdf769</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
