<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Republish</name>
   <tag></tag>
   <elementGuidId>c5318bb6-df71-446e-aef0-e26192b872b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='spCommandBar']/div/div/div/div/div/div[2]/div[3]/div/div/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ms-Button-flexContainer.flexContainer-138</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>19ac77f0-d6da-43b7-9c29-99dc0b742b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-Button-flexContainer flexContainer-138</value>
      <webElementGuid>5aa4eb3d-7bc7-46ef-b686-2948401608f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automationid</name>
      <type>Main</type>
      <value>splitbuttonprimary</value>
      <webElementGuid>712edcf3-8048-4fc6-bc2d-6956a4d8a2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Republish</value>
      <webElementGuid>a5cca239-b598-41cf-a332-afefad979813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spCommandBar&quot;)/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;ms-FocusZone css-77 ms-CommandBar root-119&quot;]/div[@class=&quot;ms-OverflowSet ms-CommandBar-secondaryCommand secondarySet-135&quot;]/div[@class=&quot;ms-OverflowSet-item item-123&quot;]/div[@class=&quot;ms-TooltipHost PublishTooltipHost PublishTooltipHostColumn root-76&quot;]/div[@class=&quot;primaryCommandBarButtonWrapper&quot;]/button[@class=&quot;ms-Button ms-Button--primary primaryButton primaryCommandBarButtonSpacing root-137&quot;]/span[@class=&quot;ms-Button-flexContainer flexContainer-138&quot;]</value>
      <webElementGuid>79d6aefc-9be0-486d-b733-a0ed799a203c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='spCommandBar']/div/div/div/div/div/div[2]/div[3]/div/div/button/span</value>
      <webElementGuid>2f42acbd-12d9-47b8-b0f2-869fa03cad97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button/span</value>
      <webElementGuid>8d09c0de-47f4-451f-b004-bf8f171554c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Republish' or . = 'Republish')]</value>
      <webElementGuid>1c4bb5ea-af75-41ea-ae42-038f65cea2d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
